- title: Saveable settings for testing
  description: Settings for camera, observatory and passbands
  source: ../stellarphot/saveable-settings.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot settings

- title: Seeing profile
  description: Choose aperture settings
  source: ../stellarphot/photometry/01-viewer-seeing-template.ipynb
  icon: ../stellarphot/stellarphot-logo.svg
  cwd: not_used
  type: notebook
  catalog: Stellarphot photometry
